export const enviroment = {
  production: false,
  apiUrl: 'https://admin.fora-poligrafia.pl',
  mailerUrl: 'https://newmailer.fora-poligrafia.pl',
  contactData: {
    email: 'kontak@fora-poligrafia.pl',
    phone: '507187527',
    openHouers: {
      monday: '08:00 - 16:00',
      tuesday: '08:00 - 16:00',
      wednesday: '08:00 - 16:00',
      thursday: '08:00 - 16:00',
      friday: '08:00 - 16:00',
      saturday: '10:00 - 14:00',
      sunday: 'nieczynne',
    },
    area: {
      city: [
        { name: 'Warszawa' },
        { name: 'Legionowo' },
        { name: 'Chotomów' },
        { name: 'Jabłonna' },
        { name: 'Wieliszew' },
        { name: 'Nieporęt' },
        { name: 'Zegrze' },
        { name: 'Skrzeszew' },
        { name: 'Janówek' },
        { name: 'Olszewnica Stara' },
        { name: 'Olszewnica Nowa' },
        { name: 'Łajski' },
        { name: 'Michałów-Reginów' },
        { name: 'Rajszew' },
        { name: 'Serock' },
        { name: 'Nowy Dwór Mazowiecki' },
        { name: 'Pomiechówek' },
        { name: 'Marki' },
        { name: 'Radzymin' },
        { name: 'Wołomin' },
        { name: 'Ząbki' },
        { name: 'Białołęka' },
        { name: 'Tarchomin' },
        { name: 'Łomianki' },
        { name: 'Izabelin' },
      ],
    },
  },
};
